<?php

namespace EGamebookBundle\Repository;

/**
 * ChaptersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChaptersRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getChapters($id){
        $qb = $this->createQueryBuilder('c')
                    ->where('c.id != :id')
                    ->setParameter('id', $id);
        return $qb;
    }
}