<?php

namespace EGamebookBundle\Repository;

/**
 * ChaptersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChaptersRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getChapters($id, $idB){
        $qb = $this->createQueryBuilder('c')
                    ->where('c.id != :id')
                    ->setParameter('id', $id)
                    ->andwhere('c.book = :book')
                    ->setParameter('book', $idB);
        return $qb;
    }
    public function getChaptersNumber($number, $idB){
        $qb = $this->createQueryBuilder('c')
            ->where('c.number = :number')
            ->setParameter('number', $number)
            ->andwhere('c.book = :id')
            ->setParameter('id', $idB);
        return $qb->getQuery()->getResult();
    }
}