<?php

namespace EGamebookBundle\Repository;

/**
 * ChaptersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChaptersRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getChapters(){
        $qb = $this->createQueryBuilder('c');
        $qb->select('c');
//        $qb->select('c')
//            ->where('chapter.id = :data.id')
//            ->setParameter('data.id', FALSE );
        return $qb;
    }
}